// Business rules are emitted as visible Notebook Script; no allocation service call.
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'../..');let Script;
vm.runInNewContext(fs.readFileSync(path.join(root,'webapp/model/Script.js'),'utf8'),{sap:{ui:{define:(_,f)=>Script=f()}},TextEncoder,TextDecoder,btoa,atob});
const rules=require('../demrevid-stepwise/rules.json');
const lineage=require('../demrevid-stepwise/lineage.json').cells;
const fields=['ACCOUNT','AUDITTRAIL','CATEGORY','COSTCENTRE','DEMREVID_KFS','FFLAS','FFLAS_SUBSET','MATCONN','TIME','PRODUCT_TYPE','GEO_DRIVERS','DOC_TYP','CONN_REG_SPLIT','LFC_WIN_SUPPLIER','MAT_GROUP_ID','REG_FFLAS_SERV','UFB_DR_ID','MATREMAP','RSP_SERVICE_ID','REV_ID_GROUP'];
const defaults=Object.fromEntries(fields.map(f=>[f,f==='GEO_DRIVERS'?'GDRVS_NA':f+'_NA']));
const constants=Object.fromEntries([...fs.readFileSync(path.join(root,'src/zcl_bn_dem_alloc.clas.abap'),'utf8').matchAll(/constants (\w+) type uj_dim_member value '([^']+)'/gi)].map(m=>[m[1],m[2]]));
const q=JSON.stringify;let lines,serial,cells=[],producers=new Map(),deps,indexes;
function e(s){lines.push(s);}function fresh(prefix='v'){return prefix+(++serial);}function val(v){return q(constants[v]||v);}
function load(n){if(lines.some(s=>s.startsWith('dataset '+n+' =')))return n;const p=producers.get(n);if(!p)throw Error('No producer '+n);deps.add(p);e(`dataset ${n} = ${q(p)} named ${q(n.toUpperCase())}`);return n;}
function pub(n){e(`publish ${n} as ${q(n.toUpperCase())}`);producers.set(n,currentId);}
function sort(n,keys){e(`sort ${n} unstable by ${keys.map(k=>k+' asc').join(', ')}`);}
function gaps(n){e('defaults '+n+' with '+Object.entries(defaults).map(([f,d])=>f+' '+q(d)).join(', '));}
function group(n,mode,keys=[]){const t=fresh('group');e(`group ${t} = ${n} ${mode}${mode==='all'?'':' '+q(keys)}`);if(mode!=='all'){gaps(t);sort(t,keys);}return t;}
function filter(n,condition){const t=fresh('filtered'),r=fresh('f');e(`filter ${t} = ${n} as ${r} where ${condition.replaceAll('$',r)}`);return t;}
function kf(n,k){return filter(n,`$.DEMREVID_KFS == ${val(k)}`);}
function replace(n,changes,condition){const r=fresh('replace');e(`for ${r} in ${n}`);if(condition)e(`if ${condition.replaceAll('$',r)}`);for(const [f,v]of Object.entries(changes))e(`${r}.${f} = ${v.replaceAll('$',r)}`);if(condition)e('end');e('end');return n;}
function find(n,keys,search='binary'){const r=fresh('found');const predicate=Object.entries(keys).map(([k,v])=>k+' = '+v).join(' and ');if(['product_members','material_members','group_members'].includes(n)){const ix=ensureIndex(n,Object.keys(keys));e(`lookup ${r} = ${ix} where ${predicate} policy first missing initial`);}else e(`find ${r} = ${n} where ${predicate} search ${search} missing initial`);return r;}
function ensureIndex(n,keys){const signature=n+':'+keys.join(',');let ix=indexes.get(signature);if(!ix){ix=fresh('ix');indexes.set(signature,ix);const stack=[];for(let i=0;i<lines.length;i++)for(const line of lines[i].split('\n')){if(/^(for|if) /.test(line))stack.push({i,line});else if(line==='end')stack.pop();}const loop=stack.find(b=>b.line.startsWith('for '));const declaration=`index ${ix} = ${n} by ${q(keys)} many`;if(loop)lines.splice(loop.i,0,declaration);else e(declaration);}return ix;}
function match(n,keys){const ix=ensureIndex(n,Object.keys(keys)),t=fresh('matches');e(`match ${t} = ${ix} where ${Object.entries(keys).map(([k,v])=>k+' = '+v).join(' and ')}`);return t;}
function copyRow(r){const c=fresh('row');e(`copy ${c} = ${r}`);return c;}
function append(n,r){e(`append ${n} row ${r}`);}function empty(n,source){e(`empty ${n} = ${source}`);return n;}
function enrich(n){load('input_data');for(const x of ['conn_reg_split','l1_l2_mapping','mat_group_mapping','product_members','material_members','group_members'])load(x);
 const rem=kf('input_data','mat_remapping'),reg=kf('input_data','kf_reg_fflas_serv_mapping'),overwrite=kf('input_data','kf_prod_type_mapping');sort(rem,['TIME','ACCOUNT','MATCONN']);sort(reg,['TIME','MATCONN','MAT_GROUP_ID']);sort(overwrite,['TIME','MATCONN']);
 const r=fresh('revenue');e(`for ${r} in ${n}`);const p=find(overwrite,{TIME:r+'.TIME',MATCONN:r+'.MATCONN'});e(`if found(${p})`);
 // Original NUM03 mapping: inspect actual stored product IDs, never invent a member.
 const mapped=find('product_members',{ID:'concat("PRODUCT_TYPE_", numeric_text('+p+'.SIGNEDDATA,3))'},'linear');e(`if found(${mapped})\n${r}.PRODUCT_TYPE = ${mapped}.ID\nelse\n${r}.PRODUCT_TYPE = ${p}.PRODUCT_TYPE\nend\nend`);
 const prod=find('product_members',{ID:r+'.PRODUCT_TYPE'},'linear');e(`${r}.REV_ID_GROUP = ${prod}.REV_ID_GROUP`);
 for(const [table,field]of [['conn_reg_split','CONN_REG_SPLIT'],['l1_l2_mapping','FFLAS_SUBSET']]){const m=find(table,{TIME:r+'.TIME',ACCOUNT:r+'.ACCOUNT'});e(`if found(${m})\n${r}.${field} = ${m}.${field}\nend`);}
 const specific=find(rem,{TIME:r+'.TIME',ACCOUNT:r+'.ACCOUNT',MATCONN:r+'.MATCONN'});e(`if found(${specific})\n${r}.MATREMAP = ${specific}.MATREMAP\nelse`);const fallback=find(rem,{TIME:r+'.TIME',ACCOUNT:q('ACCOUNT_NA'),MATCONN:r+'.MATCONN'});e(`if found(${fallback})\n${r}.MATREMAP = ${fallback}.MATREMAP\nelse\nif ${r}.MATCONN == "MATCONN_NA"\n${r}.MATREMAP = "MATREMAP_NA"\nelse\n${r}.MATREMAP = ${r}.MATCONN\nend\nend\nend`);
 e(`if ${r}.PRODUCT_TYPE == "PRODUCT_TYPE_NA" and ${r}.MATREMAP != "MATREMAP_NA"`);const m=find('material_members',{ID:r+'.MATREMAP'},'linear');e(`${r}.PRODUCT_TYPE = ${m}.PRODUCT_TYPE\nend`);
 e(`if ${r}.MATREMAP != "MATREMAP_NA"`);const gm=find('mat_group_mapping',{TIME:r+'.TIME',MATCONN:r+'.MATREMAP',ACCOUNT:q('ACCOUNT_NA')});e(`if found(${gm})\n${r}.MAT_GROUP_ID = ${gm}.MAT_GROUP_ID\nend\nelse`);const ga=find('mat_group_mapping',{TIME:r+'.TIME',MATCONN:q('MATCONN_NA'),ACCOUNT:r+'.ACCOUNT'});e(`if found(${ga})\n${r}.MAT_GROUP_ID = ${ga}.MAT_GROUP_ID\nend\nend`);
 const g=find('group_members',{ID:r+'.MAT_GROUP_ID'},'linear');e(`if not initial(${g}.REV_ID_GROUP)\n${r}.REV_ID_GROUP = ${g}.REV_ID_GROUP\nend`);
 const rg=find(reg,{TIME:r+'.TIME',MATCONN:q('MATCONN_NA'),MAT_GROUP_ID:r+'.MAT_GROUP_ID'});e(`if found(${rg})\n${r}.REG_FFLAS_SERV = ${rg}.REG_FFLAS_SERV\nelse`);const rm=find(reg,{TIME:r+'.TIME',MATCONN:r+'.MATREMAP'});e(`if found(${rm})\n${r}.REG_FFLAS_SERV = ${rm}.REG_FFLAS_SERV\nend\nend\nend`);
}
function start(i){serial=0;indexes=new Map();lines=['script version 2 compact'];deps=new Set(i>1?['step_'+String(i-1).padStart(2,'0')]:[]);currentId='step_'+String(i).padStart(2,'0');}
let currentId;
function finish(i,exports){for(const n of exports)pub(n);const control=exports.includes('new_data')?'new_data':exports.includes('sap_revenues')?'sap_revenues':null;if(control){const total=group(control,'include',['CATEGORY','TIME','ACCOUNT','MATCONN','AUDITTRAIL','DEMREVID_KFS']);e(`show ${total} as "CONTROL_TOTALS"`);}const script=lines.join('\n')+'\n';let source;try{source=Script.compile(script);}catch(err){source=''; console.error(currentId+': '+err.message);}const item=lineage[i-1];cells.push({id:currentId,title:String(i).padStart(2,'0')+' · '+rules[item.stage].title,explanation:rules[item.stage].rule+'\n\nCheck: '+rules[item.stage].check,dependencies:[...deps],source,script});}
function selectMethods(supplier=false){load('sap_revenues_consol');load('new_data');const tables=supplier?['rsp_supplier_material_ratio','rsp_supplier_gl_ratio','cal_supplier_gl_ratio','cal_supplier_conn_seg_ratio']:['rsp_location_material_ratio','rsp_location_gl_ratio','cal_location_gl_ratio','cal_location_conn_seg_ratio'];tables.forEach(load);const r=fresh('base');e(`for ${r} in sap_revenues_consol copy`);e(`${r}.DEMREVID_KFS = ${val(supplier?'kf_supplier_split_index':'kf_loc_split_index')}`);const method=fresh('method');e(`let ${method} = 5`);for(let j=0;j<4;j++){e(`if ${method} == 5`);const key=j===0?{TIME:r+'.TIME',...(supplier?{ACCOUNT:r+'.ACCOUNT'}:{}),MATCONN:r+'.MATCONN'}:j===3?{TIME:r+'.TIME',CONN_REG_SPLIT:r+'.CONN_REG_SPLIT'}:{TIME:r+'.TIME',ACCOUNT:r+'.ACCOUNT'};const f=find(tables[j],key);e(`if found(${f})\n${method} = ${j+1}\nend\nend`);}e(`${r}.SIGNEDDATA = integer(${method})`);append('new_data',r);e('end');}
function resolveRatios(supplier=false){load('new_data');const out=supplier?'supplier_ratios':'rsp_split_ratios';empty(out,'new_data');const tables=supplier?['rsp_supplier_material_ratio','rsp_supplier_gl_ratio','cal_supplier_gl_ratio','cal_supplier_conn_seg_ratio']:['rsp_location_material_ratio','rsp_location_gl_ratio','cal_location_gl_ratio','cal_location_conn_seg_ratio'];tables.forEach(load);const selected=kf('new_data',supplier?'kf_supplier_split_index':'kf_loc_split_index');const r=fresh('selected');e(`for ${r} in ${selected} copy\n${r}.DEMREVID_KFS = ${val(supplier?'kf_supplier_split_ratio':'kf_ratios_for_split')}`);for(let j=0;j<4;j++){e(`if integer(${r}.SIGNEDDATA) == ${j+1}`);let source=tables[j];const key=j===0?{TIME:r+'.TIME',...(supplier?{ACCOUNT:r+'.ACCOUNT'}:{}),MATCONN:r+'.MATCONN'}:j===3?{CONN_REG_SPLIT:r+'.CONN_REG_SPLIT',TIME:r+'.TIME'}:{ACCOUNT:r+'.ACCOUNT',TIME:r+'.TIME'};
 if(!supplier&&j===0){const over=find(source,{...key,AUDITTRAIL:q('DEMREVID_LOC_RATIO_OVERWRITE')},'linear');const trail=fresh('trail');e(`let ${trail} = "DEMREVID_RSP_BILLING"\nif found(${over})\n${trail} = "DEMREVID_LOC_RATIO_OVERWRITE"\nend`);key.AUDITTRAIL=trail;}
 const rows=match(source,key),m=fresh('ratio');e(`for ${m} in ${rows}`);const c=copyRow(r);e(`${c}.${supplier?'LFC_WIN_SUPPLIER':'GEO_DRIVERS'} = ${m}.${supplier?'LFC_WIN_SUPPLIER':'GEO_DRIVERS'}\n${c}.SIGNEDDATA = ${m}.SIGNEDDATA`);append(out,c);e('end\nend');}e('end');if(supplier)sort(out,['TIME','ACCOUNT','MATCONN']);e(`append new_data from ${out}`);return out;}
function divideTable(n,d,keys){const r=fresh('divide');e(`for ${r} in ${n}`);const f=find(d,Object.fromEntries(keys.map(k=>[k,r+'.'+k])));e(`divide ${r}.SIGNEDDATA by ${f}.SIGNEDDATA using float onzero keep\nend`);}
function ratio(n,keys){const total=group(n,'include',keys);divideTable(n,total,keys);const sums=group(n,'include',keys);sort(n,keys);const r=fresh('sum');e(`for ${r} in ${sums}\nif ${r}.SIGNEDDATA != 1 and not initial(${r}.SIGNEDDATA)`);const first=find(n,Object.fromEntries(keys.map(k=>[k,r+'.'+k])),'linear');e(`if found(${first})\n${first}.SIGNEDDATA = ${first}.SIGNEDDATA + (1 - ${r}.SIGNEDDATA)\nend\nend\nend`);return n;}

start(1);
e('reference model source_model = DEMREVID\ndata raw_source = source_model limit 1000000\nassert count(raw_source) <= number(input("READ_LIMIT")) message "Complete source exceeds configured READ_LIMIT"');
e(`project complete_source_data = raw_source fields ${q([...fields,'SIGNEDDATA'])}`);
for(const [alias,dim]of [['product_members','PRODUCT_TYPE'],['material_members','MATCONN'],['group_members','MAT_GROUP_ID']]){e(`dimension dim_${alias} = DEMREVID-${dim}\nmembers ${alias} = dim_${alias}`);pub(alias);}
e('dimension audits = DEMREVID-AUDITTRAIL\ndimension measures = DEMREVID-DEMREVID_KFS');
e('let input_ids = children(audits, "DEMREVID_INPUT", "PARENTH1")\nlet output_ids = children(audits, "DEMREVID_OUTPUT", "PARENTH1")\nlet revenue_ids = children(measures, "DEMREVID004", "PARENTH1")');
const scoped=filter('complete_source_data','(is_in($.TIME, range("TIME")) or $.TIME == "TIME_NA") and $.CATEGORY == member("CATEGORY")');
e(`filter input_data = ${scoped} as source_input where is_in(source_input.AUDITTRAIL, input_ids)\nfilter output_data = ${scoped} as source_output where is_in(source_output.AUDITTRAIL, output_ids)\nempty new_data = complete_source_data`);
const sr=filter('input_data','is_in($.DEMREVID_KFS, revenue_ids)'),sg=group(sr,'exclude',['COSTCENTRE','DOC_TYP','AUDITTRAIL']);replace(sg,{AUDITTRAIL:val('audit_dnrid_calc')});e(`copy sap_revenues = ${sg}`);
const drivers=[['conn_reg_split','kf_conn_region_mapping',['TIME','ACCOUNT']],['l1_l2_mapping','kf_l1_l2_mapping',['TIME','ACCOUNT']],['mat_group_mapping','kf_mat_group_mapping',['TIME','MATCONN','ACCOUNT']],['rsp_location_material_ratio','kf_rsp_loc_ratio_mat',['TIME','MATCONN']],['rsp_location_gl_ratio','kf_rsp_loc_ratio_gl',['TIME','ACCOUNT']],['cal_location_gl_ratio','kf_cal_loc_ratio_gl',['TIME','ACCOUNT']],['cal_location_conn_seg_ratio','kf_cal_loc_ratio_conn_reg',['TIME','CONN_REG_SPLIT']],['rsp_supplier_material_ratio','kf_rsp_supplier_ratio_mat',['TIME','ACCOUNT','MATCONN']],['rsp_supplier_gl_ratio','kf_rsp_supplier_ratio_gl',['ACCOUNT','TIME']],['cal_supplier_gl_ratio','kf_cal_supplier_ratio_gl',['ACCOUNT','TIME']],['cal_supplier_conn_seg_ratio','kf_cal_supplier_ratio_conn_reg',['CONN_REG_SPLIT','TIME']]];
for(const [n,k,keys]of drivers){const t=kf('input_data',k);e(`copy ${n} = ${t}`);sort(n,keys);}
e('dimension products = DEMREVID-PRODUCT_TYPE\nlet access_ids = children(products, "PRODUCT_TYPE_ACCESS", "PARENTH1")\ntable access_members columns ID member\nrow access_row like access_members\nfor access_id in access_ids\naccess_row.ID = access_id\nappend access_members row access_row\nend');pub('access_members');
finish(1,['complete_source_data','input_data','output_data','new_data','sap_revenues',...drivers.map(d=>d[0])]);
start(2);load('sap_revenues');load('new_data');enrich('sap_revenues');e('append new_data from sap_revenues');finish(2,['sap_revenues','new_data']);
start(3);load('sap_revenues');const cons=group('sap_revenues','exclude',['DEMREVID_KFS']);e(`copy sap_revenues_consol = ${cons}`);finish(3,['sap_revenues_consol']);
start(4);selectMethods();finish(4,['new_data']);
start(5);resolveRatios();finish(5,['new_data','rsp_split_ratios']);
start(6);load('input_data');load('new_data');const bill=filter('input_data',`$.DEMREVID_KFS == ${val('kf_rsp_bill_prod_type')} and is_in($.DOC_TYP, ["RS","AD","AC"]) and $.UFB_DR_ID != "UFBDRID006" and $.UFB_DR_ID != "UFB_DR_ID_NA"`);const billed=group(bill,'exclude',['DOC_TYP','UFB_DR_ID','LFC_WIN_SUPPLIER']);replace(billed,{DEMREVID_KFS:val('kf_rsp_bill_with_loc'),AUDITTRAIL:val('audit_dnrid_calc')});enrich(billed);e(`append new_data from ${billed}`);finish(6,['new_data']);
for(let stage=7;stage<=8;stage++){start(stage);load('new_data');load('sap_revenues');load('rsp_split_ratios');let already;if(stage===7){already=group(kf('new_data','kf_rsp_bill_with_loc'),'exclude',['GEO_DRIVERS']);sort(already,['TIME','ACCOUNT','MATCONN']);}const src=kf('sap_revenues',stage===7?'rsp_billing':'kf_rsp_not_billed'),r=fresh('revenue');e(`for ${r} in ${src} copy`);if(already){const f=find(already,{TIME:r+'.TIME',ACCOUNT:r+'.ACCOUNT',MATCONN:r+'.MATCONN'});e(`if found(${f})\n${r}.SIGNEDDATA = ${r}.SIGNEDDATA - ${f}.SIGNEDDATA\nend`);}e(`if not initial(${r}.SIGNEDDATA)`);const rows=match('rsp_split_ratios',{MATCONN:r+'.MATCONN',ACCOUNT:r+'.ACCOUNT',TIME:r+'.TIME'}),m=fresh('ratio');e(`for ${m} in ${rows}`);const c=copyRow(r);e(`${c}.DEMREVID_KFS = ${val(stage===7?'kf_rsp_bill_no_loc':'kf_rsp_not_billed_loc')}\n${c}.GEO_DRIVERS = ${m}.GEO_DRIVERS\n${c}.SIGNEDDATA = ${c}.SIGNEDDATA * ${m}.SIGNEDDATA`);append('new_data',c);e('end\nend\nend');finish(stage,['new_data']);}
start(9);load('input_data');load('new_data');load('sap_revenues_consol');empty('fflas_month_ratio','new_data');const mapping=filter('input_data',`is_in($.DEMREVID_KFS,[${val('kf_fflas_grouping')},${val('kf_fflas_monthly_pct')}])`);sort(mapping,['MATCONN','ACCOUNT','DEMREVID_KFS','TIME']);e('for revenue in sap_revenues_consol');
for(const branch of ['material','account']){if(branch==='account')e('else');const key={MATCONN:branch==='material'?'revenue.MATCONN':q('MATCONN_NA'),ACCOUNT:branch==='material'?q('ACCOUNT_NA'):'revenue.ACCOUNT',DEMREVID_KFS:val('kf_fflas_grouping'),TIME:'revenue.TIME'};const found=find(mapping,key);e(`if found(${found})`);const c=copyRow('revenue');e(`${c}.DEMREVID_KFS = ${found}.DEMREVID_KFS\n${c}.SIGNEDDATA = ${found}.SIGNEDDATA`);append('new_data',c);const monthly=find(mapping,{...key,DEMREVID_KFS:val('kf_fflas_monthly_pct')});e(`if found(${monthly})`);const mc=copyRow('revenue');e(`${mc}.DEMREVID_KFS = ${monthly}.DEMREVID_KFS\n${mc}.SIGNEDDATA = ${monthly}.SIGNEDDATA`);append('new_data',mc);append('fflas_month_ratio',mc);e('end');}e('end\nend\nend');finish(9,['new_data','fflas_month_ratio']);
start(10);load('new_data');const loc=filter('new_data',`$.DEMREVID_KFS >= ${val('kf_rsp_bill_with_loc')} and $.DEMREVID_KFS <= ${val('kf_rsp_not_billed_loc')}`);replace(loc,{DEMREVID_KFS:val('kf_fflas_revenue')});replace(loc,{FFLAS:val('fflas_pq')},`$.GEO_DRIVERS >= ${val('geo_ronz')} and $.GEO_DRIVERS <= ${val('geo_ufb')}`);replace(loc,{FFLAS:val('fflas_id')},`$.GEO_DRIVERS == ${val('geo_lfc')}`);const byLoc=group(loc,'all'),allocation=kf('new_data','kf_fflas_monthly_pct');sort(allocation,['TIME','ACCOUNT','MATCONN']);e(`copy allocated = ${byLoc}\nfor allocated_row in allocated`);const pct=find(allocation,{TIME:'allocated_row.TIME',ACCOUNT:'allocated_row.ACCOUNT',MATCONN:'allocated_row.MATCONN'});e(`allocated_row.SIGNEDDATA = allocated_row.SIGNEDDATA * ${pct}.SIGNEDDATA\nend`);const nz=filter('allocated','not initial($.SIGNEDDATA)'),geo=group(nz,'exclude',['FFLAS']);sort(geo,['TIME','ACCOUNT','MATCONN','GEO_DRIVERS']);e(`copy residual = ${byLoc}`);sort('residual',['TIME','ACCOUNT','MATCONN','GEO_DRIVERS']);e('for residual_row in residual');const g=find(geo,{TIME:'residual_row.TIME',ACCOUNT:'residual_row.ACCOUNT',MATCONN:'residual_row.MATCONN',GEO_DRIVERS:'residual_row.GEO_DRIVERS'});e(`if found(${g})\nresidual_row.SIGNEDDATA = residual_row.SIGNEDDATA - ${g}.SIGNEDDATA\nend\nresidual_row.FFLAS = ${val('fflas_non')}\nend`);const non=filter('residual','not initial($.SIGNEDDATA)');e(`append new_data from ${nz}\nappend new_data from ${non}`);finish(10,['new_data']);
start(11);load('new_data');const ff=kf('new_data','kf_fflas_revenue'),den=group(ff,'exclude',['GEO_DRIVERS','FFLAS']);sort(den,['TIME','ACCOUNT','MATCONN']);const pq=group(filter(ff,`$.FFLAS == ${val('fflas_pq')}`),'exclude',['GEO_DRIVERS']);sort(pq,['TIME','ACCOUNT','MATCONN']);divideTable(pq,den,['TIME','ACCOUNT','MATCONN']);replace(pq,{DEMREVID_KFS:val('kf_pq_fflas_pct')});e(`append new_data from ${pq}`);finish(11,['new_data']);
start(12);selectMethods(true);finish(12,['new_data']);
start(13);resolveRatios(true);finish(13,['new_data','supplier_ratios']);
start(14);load('new_data');load('supplier_ratios');empty('supplier_allocated','new_data');e(`for original in new_data\nif original.DEMREVID_KFS == ${val('kf_fflas_revenue')} and original.FFLAS == ${val('fflas_id')}`);const foundSupplier=find('supplier_ratios',{TIME:'original.TIME',ACCOUNT:'original.ACCOUNT',MATCONN:'original.MATCONN'});e(`if found(${foundSupplier})`);const matches=match('supplier_ratios',{TIME:'original.TIME',ACCOUNT:'original.ACCOUNT',MATCONN:'original.MATCONN'});e(`for supplier_row in ${matches}`);const split=copyRow('original');e(`${split}.SIGNEDDATA = original.SIGNEDDATA * supplier_row.SIGNEDDATA\n${split}.LFC_WIN_SUPPLIER = supplier_row.LFC_WIN_SUPPLIER`);append('supplier_allocated',split);e('end\ndelete original\nend\nend\nend\nappend new_data from supplier_allocated');finish(14,['new_data']);
start(15);load('input_data');load('new_data');load('sap_revenues_consol');const price=kf('input_data','sap_price');sort(price,['TIME','MATCONN']);e('for revenue in sap_revenues_consol copy');const pr=find(price,{TIME:'revenue.TIME',MATCONN:'revenue.MATCONN'});e(`if found(${pr})\nrevenue.DEMREVID_KFS = ${pr}.DEMREVID_KFS\nrevenue.SIGNEDDATA = ${pr}.SIGNEDDATA`);append('new_data','revenue');e('end\nend');finish(15,['new_data']);

function collectRow(target,row){const f=find(target,Object.fromEntries(fields.map(k=>[k,row+'.'+k])),'linear');e(`if found(${f})\n${f}.SIGNEDDATA = ${f}.SIGNEDDATA + ${row}.SIGNEDDATA\nelse`);append(target,row);e('end');}
function parameterRange(parameter,boolean=false){const raw=fresh('raw'),parts=fresh('parts'),table=fresh('range'),row=fresh('range_row'),value=fresh('value');e(`let ${raw} = input(${q(parameter)})`);if(boolean)e(`if ${raw} == "true"\n${raw} = "1"\nend\nif ${raw} == "false"\n${raw} = "0"\nend`);e(`let ${parts} = split(${raw},",")\ntable ${table} columns ID member\nrow ${row} like ${table}\nfor ${value} in ${parts}\n${row}.ID = no_gaps(${value})\nappend ${table} row ${row}\nend`);sort(table,['ID']);e(`deduplicate ${table} adjacent by ["ID"]`);return table;}
start(16);load('new_data');load('input_data');load('sap_revenues');
const credit=filter('new_data',`$.DEMREVID_KFS == ${val('kf_fflas_revenue')} and $.ACCOUNT == "001054200" and is_in($.PRODUCT_TYPE,[${val('access_rental')},${val('bandwidth')}])`);
replace(credit,{AUDITTRAIL:q('DEMREVID_CALC_HSNS_CREDIT')});
// The generic replace helper takes expressions containing its own row alias.
e(`for credit_row in ${credit}\ncredit_row.SIGNEDDATA = credit_row.SIGNEDDATA * -1\nend\nappend new_data from ${credit}`);
const upload=kf('input_data','kf_hsns_premium_upload');replace(upload,{AUDITTRAIL:q('DEMREVID_CALC_HSNS'),DEMREVID_KFS:val('rsp_billing')});const uploaded=group(upload,'exclude',['UFB_DR_ID']);enrich(uploaded);sort(uploaded,['TIME','RSP_SERVICE_ID','PRODUCT_TYPE','FFLAS']);
e(`for bandwidth_row in ${uploaded}\nif bandwidth_row.PRODUCT_TYPE == ${val('bandwidth')}`);const access=find(uploaded,{TIME:'bandwidth_row.TIME',RSP_SERVICE_ID:'bandwidth_row.RSP_SERVICE_ID',PRODUCT_TYPE:val('access_rental'),FFLAS:'bandwidth_row.FFLAS'},'linear');e(`if found(${access})\nbandwidth_row.MAT_GROUP_ID = ${access}.MAT_GROUP_ID\nbandwidth_row.RSP_SERVICE_ID = "RSP_SERVICE_ID_NA"\nend\nend\nend`);
const groupedUpload=group(uploaded,'all');e(`append new_data from ${groupedUpload}`);
e(`copy hsns_fflas_allocation = ${groupedUpload}`);replace('hsns_fflas_allocation',{DEMREVID_KFS:val('kf_fflas_revenue')});const hsnsInitial=group('hsns_fflas_allocation','all');
// Original exclusions apply to ratio drivers, not to the already copied billed output.
const hsnsLocations=parameterRange('HSNS_REALLOC_LOCATIONS');e(`copy eligible = ${groupedUpload}\nfor eligible_row in eligible\nif eligible_row.FFLAS == ${val('fflas_id')}`);const permitted=find(hsnsLocations,{ID:'eligible_row.LFC_WIN_SUPPLIER'},'linear');e(`if not found(${permitted})\ndelete eligible_row\nend\nend\nend`);const eligible='eligible';
const materialRatio=ratio(group(eligible,'include',['TIME','MATCONN','FFLAS','LFC_WIN_SUPPLIER']),['TIME','MATCONN']);const groupRatio=ratio(group(eligible,'include',['TIME','MAT_GROUP_ID','FFLAS','LFC_WIN_SUPPLIER']),['TIME','MAT_GROUP_ID']);
const accruals=filter('sap_revenues',`$.ACCOUNT == "001054200" and is_in($.PRODUCT_TYPE,[${val('access_rental')},${val('bandwidth')}]) and $.DEMREVID_KFS == ${val('accrual')}`);replace(accruals,{AUDITTRAIL:q('DEMREVID_CALC_HSNS')});empty('accrual_allocation','new_data');
e(`for accrued in ${accruals}`);const matFound=find(materialRatio,{TIME:'accrued.TIME',MATCONN:'accrued.MATCONN'},'linear');e(`if found(${matFound})`);
for(const [source,key]of [[materialRatio,'MATCONN'],[groupRatio,'MAT_GROUP_ID']]){if(key==='MAT_GROUP_ID')e('else');const matches=match(source,{TIME:'accrued.TIME',[key]:'accrued.'+key}),r=fresh('ratio');e(`for ${r} in ${matches}`);const c=copyRow('accrued');e(`${c}.LFC_WIN_SUPPLIER = ${r}.LFC_WIN_SUPPLIER\n${c}.FFLAS = ${r}.FFLAS\n${c}.SIGNEDDATA = accrued.SIGNEDDATA * ${r}.SIGNEDDATA`);append('accrual_allocation',c);e('end');}
e(`end\nend\nappend new_data from accrual_allocation\nappend ${hsnsInitial} from accrual_allocation`);replace(hsnsInitial,{DEMREVID_KFS:val('kf_fflas_revenue')});const hsnsFinal=group(hsnsInitial,'all');e(`append new_data from ${hsnsFinal}`);finish(16,['new_data']);

start(17);load('sap_revenues');load('new_data');empty('fflas_ratios','new_data');empty('skipped_materials','new_data');
const base=group('sap_revenues','include',['CATEGORY','TIME','ACCOUNT','MATCONN','MAT_GROUP_ID']);replace(base,{AUDITTRAIL:val('audit_dnrid_calc'),DEMREVID_KFS:val('kf_fflas_ratios_material')});e(`show ${base} as "RATIO_BASE_BEFORE_EXCLUSIONS"`);
const skipIds=parameterRange('FFLASMATGROUPSID'),skipFlags=parameterRange('FFLASMATGROUPS',true);e(`table positioned_flags columns POSITION integer, FLAG member\nrow positioned_flag like positioned_flags\nlet flag_position = 0\nfor flag_value in ${skipFlags}\nflag_position = flag_position + 1\npositioned_flag.POSITION = integer(flag_position)\npositioned_flag.FLAG = flag_value.ID\nappend positioned_flags row positioned_flag\nend\ntable skip_members columns ID member\nrow skip_member like skip_members\nlet skip_position = 0\nfor skip_id in ${skipIds}\nskip_position = skip_position + 1`);const sf=find('positioned_flags',{POSITION:'integer(skip_position)'},'linear');e(`if found(${sf})\nif not initial(${sf}.FLAG)\nif signed(${sf}.FLAG) != 0\nskip_member.ID = skip_id.ID\nappend skip_members row skip_member\nend\nend\nend\nend`);
e(`for base_row in ${base}`);const skip=find('skip_members',{ID:'base_row.MAT_GROUP_ID'},'linear');e(`if found(${skip})`);const c=copyRow('base_row');e(`${c}.MAT_GROUP_ID = ""\n${c}.DEMREVID_KFS = ${val('kf_fflas_ratio_skipped')}\n${c}.FFLAS = ${val('fflas_na')}\n${c}.SIGNEDDATA = 1`);const exists=find('skipped_materials',{TIME:c+'.TIME',ACCOUNT:c+'.ACCOUNT',MATCONN:c+'.MATCONN'},'linear');e(`if not found(${exists})`);append('skipped_materials',c);e('end\ndelete base_row\nend\nend');e(`show skipped_materials as "SKIPPED_MATERIAL_FLAGS"\nshow ${base} as "RATIO_BASE_AFTER_EXCLUSIONS"`);
const denominators=group(base,'exclude',['MAT_GROUP_ID']);const numerators=group(kf('new_data','kf_fflas_revenue'),'include',['CATEGORY','TIME','ACCOUNT','MATCONN','FFLAS','MAT_GROUP_ID']);replace(numerators,{AUDITTRAIL:val('audit_dnrid_calc'),DEMREVID_KFS:val('kf_fflas_ratios_material')});e(`show ${numerators} as "FFLAS_REVENUE_NUMERATORS"\nfor denominator in ${denominators} copy\nif not initial(denominator.SIGNEDDATA)\nnative remainder = denominator.SIGNEDDATA`);
const nums=match(numerators,{TIME:'denominator.TIME',ACCOUNT:'denominator.ACCOUNT',MATCONN:'denominator.MATCONN'});e(`for numerator in ${nums} copy\nremainder = remainder - numerator.SIGNEDDATA\nnumerator.SIGNEDDATA = numerator.SIGNEDDATA / denominator.SIGNEDDATA`);append('fflas_ratios','numerator');e('end\nif not initial(remainder)\ndenominator.SIGNEDDATA = remainder / denominator.SIGNEDDATA\ndenominator.FFLAS = "FFLASNON"');collectRow('fflas_ratios','denominator');e('end\nend\nend\nshow fflas_ratios as "RATIOS_BEFORE_ROUNDING"');
const sums=filter(group('fflas_ratios','exclude',['FFLAS','MAT_GROUP_ID']),'$.SIGNEDDATA != 1');sort('fflas_ratios',['TIME','ACCOUNT','MATCONN']);e(`for ratio_sum in ${sums}`);const correction=find('fflas_ratios',{TIME:'ratio_sum.TIME',ACCOUNT:'ratio_sum.ACCOUNT',MATCONN:'ratio_sum.MATCONN'});e(`if found(${correction})\nlet balance = signed(1 - ratio_sum.SIGNEDDATA)\n${correction}.SIGNEDDATA = ${correction}.SIGNEDDATA + balance\nend\nend\nappend fflas_ratios from skipped_materials\nshow fflas_ratios as "RATIOS_AND_FLAGS"\nappend new_data from fflas_ratios`);finish(17,['new_data']);

start(18);load('new_data');load('input_data');const revenueSummary=group(kf('new_data','kf_fflas_revenue'),'exclude',['ACCOUNT','AUDITTRAIL','GEO_DRIVERS','CONN_REG_SPLIT','RSP_SERVICE_ID','REV_ID_GROUP','MATCONN']);replace(revenueSummary,{DEMREVID_KFS:val('kf_alloc_rev_summary'),AUDITTRAIL:val('audit_dnrid_calc')});replace(revenueSummary,{LFC_WIN_SUPPLIER:q('LFC_WIN_SUPPLIER_NA')},`$.FFLAS == ${val('fflas_pq')}`);const tr=group(revenueSummary,'all');e(`copy transposed_revenues = ${tr}\ncopy reporting_aux = transposed_revenues`);replace('reporting_aux',{MATREMAP:q('MATREMAP_NA')},'$.MAT_GROUP_ID != "MAT_GROUP_ID_NA"');const summary=group('reporting_aux','all'),hidden=kf('input_data','kf_hidden_mat_group');e(`for visible in ${summary}`);const h=find(hidden,{MAT_GROUP_ID:'visible.MAT_GROUP_ID'},'linear');e(`if found(${h})\ndelete visible\nend\nend\nappend new_data from ${summary}`);finish(18,['new_data','transposed_revenues']);

start(19);load('input_data');load('new_data');load('transposed_revenues');load('access_members');const prices=kf('input_data','sap_price'),oneOff=kf('input_data','mat_remapping');sort(prices,['TIME','MATCONN']);sort(oneOff,['TIME','MATREMAP']);empty('conn_prices','new_data');e('for access_revenue in transposed_revenues copy');const acc=find('access_members',{ID:'access_revenue.PRODUCT_TYPE'},'linear');e(`if found(${acc})`);const mapped=find(oneOff,{TIME:'access_revenue.TIME',MATREMAP:'access_revenue.MATREMAP'});e(`if not initial(${mapped}.MATCONN)`);const cp=find(prices,{TIME:'access_revenue.TIME',MATCONN:mapped+'.MATCONN'});e(`access_revenue.DEMREVID_KFS = ${val('conn_price_kf')}\naccess_revenue.SIGNEDDATA = ${cp}.SIGNEDDATA`);append('conn_prices','access_revenue');append('conn_prices','access_revenue');e('end');const ap=find(prices,{TIME:'access_revenue.TIME',MATCONN:'access_revenue.MATREMAP'});e(`access_revenue.DEMREVID_KFS = ${val('access_price_kf')}\naccess_revenue.SIGNEDDATA = ${ap}.SIGNEDDATA`);append('conn_prices','access_revenue');e('end\nend');replace('conn_prices',{MATREMAP:q('MATREMAP_NA')},'$.MAT_GROUP_ID != "MAT_GROUP_ID_NA"');e('sort conn_prices unstable by TIME asc, FFLAS asc, DEMREVID_KFS asc, MATREMAP asc, MAT_GROUP_ID asc, SIGNEDDATA desc\ndeduplicate conn_prices adjacent by ["TIME","FFLAS","DEMREVID_KFS","MATREMAP","MAT_GROUP_ID"]\nappend new_data from conn_prices');finish(19,['new_data']);

start(20);load('input_data');load('new_data');load('complete_source_data');load('transposed_revenues');
const connCurrent=filter('input_data',`$.DEMREVID_KFS == ${val('kf_monthly_cal_conn')} and $.PRODUCT_TYPE != ${val('bandwidth')}`);replace(connCurrent,{LFC_WIN_SUPPLIER:q('LFC_WIN_SUPPLIER_NA')},`$.FFLAS == ${val('fflas_pq')}`);const current=group(connCurrent,'all');
e(`if count(${current}) > 0`);enrich(current);replace(current,{MATREMAP:q('MATREMAP_NA')},'$.MAT_GROUP_ID != "MAT_GROUP_ID_NA"');const curr=group(current,'include',['TIME','FFLAS','MATREMAP','MAT_GROUP_ID','LFC_WIN_SUPPLIER']);const times=group(curr,'include',['TIME']);e(`for offset_row in ${times}\noffset_row.TIME = offset(offset_row.TIME,-1)\nend\nsort ${times} unstable by TIME desc\nlet prior_period = ""\nfor offset_time in ${times}\nprior_period = text(offset_time.TIME)\nbreak\nend`);
const priorRaw=filter('complete_source_data',`$.DEMREVID_KFS == ${val('kf_monthly_cal_conn')} and $.TIME == prior_period and $.CATEGORY == member("CATEGORY") and $.PRODUCT_TYPE != ${val('bandwidth')}`);e(`for shifted_prior in ${priorRaw}\nshifted_prior.TIME = offset(shifted_prior.TIME,1)\nend`);replace(priorRaw,{LFC_WIN_SUPPLIER:q('LFC_WIN_SUPPLIER_NA')},`$.FFLAS == ${val('fflas_pq')}`);const priorGrouped=group(priorRaw,'all');enrich(priorGrouped);replace(priorGrouped,{MATREMAP:q('MATREMAP_NA')},'$.MAT_GROUP_ID != "MAT_GROUP_ID_NA"');const prior=group(priorGrouped,'include',['TIME','FFLAS','MATREMAP','MAT_GROUP_ID','LFC_WIN_SUPPLIER']);e(`copy next_current = ${curr}\nfor next_row in next_current\nnext_row.TIME = offset(next_row.TIME,1)\nend\nappend ${prior} from next_current`);
const hiddenConn=kf('input_data','kf_hidden_conn');sort(hiddenConn,['TIME','MAT_GROUP_ID']);const revNoProduct=group('transposed_revenues','exclude',['PRODUCT_TYPE']);replace(revNoProduct,{MATREMAP:q('MATREMAP_NA')},'$.MAT_GROUP_ID != "MAT_GROUP_ID_NA"');const rev=group(revNoProduct,'all');e(`for previous_summary in transposed_revenues\ndelete previous_summary\nend\nappend transposed_revenues from ${rev}`);empty('transposed_conn','new_data');e(`for report_row in ${rev} copy`);const hide=find(hiddenConn,{TIME:'report_row.TIME',MAT_GROUP_ID:'report_row.MAT_GROUP_ID'});e(`if ${hide}.SIGNEDDATA == 1\ncontinue\nend`);const connKeys=Object.fromEntries(['TIME','FFLAS','MATREMAP','MAT_GROUP_ID','LFC_WIN_SUPPLIER'].map(k=>[k,'report_row.'+k]));const close=find(curr,connKeys,'linear');e(`if found(${close})\nreport_row.SIGNEDDATA = ${close}.SIGNEDDATA\nreport_row.DEMREVID_KFS = ${val('kf_conn_closing')}`);append('transposed_conn','report_row');e('end');const open=find(prior,connKeys,'linear');e(`if found(${open})\nreport_row.SIGNEDDATA = ${open}.SIGNEDDATA\nreport_row.DEMREVID_KFS = ${val('kf_conn_opening')}`);append('transposed_conn','report_row');e(`${open}.SIGNEDDATA = 0\nend\nend`);
const remaining=filter(prior,'not initial($.SIGNEDDATA)');sort(remaining,['TIME','FFLAS','MATREMAP','MAT_GROUP_ID','LFC_WIN_SUPPLIER']);const closing=filter('complete_source_data',`$.DEMREVID_KFS == ${val('kf_conn_closing')} and $.TIME == prior_period and $.CATEGORY == member("CATEGORY")`);e(`for prior_closing in ${closing} copy\nprior_closing.TIME = offset(prior_closing.TIME,1)\nprior_closing.DEMREVID_KFS = ${val('kf_conn_opening')}`);const carryKeys=Object.fromEntries(['TIME','FFLAS','MATREMAP','MAT_GROUP_ID','LFC_WIN_SUPPLIER'].map(k=>[k,'prior_closing.'+k]));const carry=find(remaining,carryKeys);e(`if not found(${carry})\ncontinue\nend`);append('transposed_conn','prior_closing');const carryClose=find(curr,carryKeys,'linear');e(`if found(${carryClose})\nprior_closing.SIGNEDDATA = ${carryClose}.SIGNEDDATA\nprior_closing.DEMREVID_KFS = ${val('kf_conn_closing')}`);append('transposed_conn','prior_closing');e('end\nend');
const addsCurrent=kf('input_data','kf_add_conn_mat_group'),addsPrior=filter('complete_source_data',`$.DEMREVID_KFS == ${val('kf_add_conn_mat_group')} and $.TIME == prior_period and $.CATEGORY == member("CATEGORY")`);e(`for prior_add in ${addsPrior}\nprior_add.TIME = offset(prior_add.TIME,1)\nend`);sort(addsCurrent,['TIME','FFLAS','MAT_GROUP_ID']);sort(addsPrior,['TIME','FFLAS','MAT_GROUP_ID']);empty('additional_connections','new_data');const connNoProduct=group('transposed_conn','exclude',['PRODUCT_TYPE']);e(`for additional in ${connNoProduct} copy`);
for(const [measure,source]of [['kf_conn_closing',addsCurrent],['kf_conn_opening',addsPrior]]){e(`if additional.DEMREVID_KFS == ${val(measure)}`);const a=find(source,{TIME:'additional.TIME',FFLAS:'additional.FFLAS',MAT_GROUP_ID:'additional.MAT_GROUP_ID'});e(`additional.SIGNEDDATA = ${a}.SIGNEDDATA\nif not initial(additional.SIGNEDDATA)`);append('additional_connections','additional');if(measure==='kf_conn_closing'){const c=copyRow('additional');e(`${c}.DEMREVID_KFS = ${val('kf_output_add_conn_mat_group')}`);append('additional_connections',c);}e('end\nend');}e(`end\nfor adjustment in additional_connections`);collectRow('transposed_conn','adjustment');e('end');sort('transposed_conn',fields);e('append new_data from transposed_conn\nend');
// Preserve the changed transposed-revenue state produced by the original method.
// Only consumed by diagnostics after this final business stage.
finish(20,['new_data','transposed_revenues']);

start(21);load('new_data');load('output_data');e('copy final_replacement = new_data\nchanges final_delta = final_replacement against output_data mode legacy\npublish final_replacement as "FINAL_REPLACEMENT"\npublish final_delta as "FINAL_DELTA"\nshow final_replacement as "FINAL_REPLACEMENT"\nshow final_delta as "FINAL_DELTA"\nmessage "Simulation only: no financial posting."');
const finalScript=lines.join('\n')+'\n';cells.push({id:'reconcile',title:'21 · Final result and change-set',explanation:'Complete replacement values and legacy changes, including zero clears for disappeared records. Simulation only.',dependencies:[...deps],source:Script.compile(finalScript),script:finalScript});
fs.mkdirSync(path.join(__dirname,'cells'),{recursive:true});for(const c of cells)fs.writeFileSync(path.join(__dirname,'cells',c.id+'.bns'),c.script);
const seed=JSON.parse(fs.readFileSync(path.join(root,'examples/demrevid-stepwise/definition.draft.json'),'utf8'));
seed.title='DEMREVID003 - Script allocation';seed.explanation='One notebook, 21 visible Script stages. Calculation and complete datasets remain on SAP. Compare results before using for financial posting.';seed.inputs.find(i=>i.name==='TIME').selected=['2026.006'];seed.inputs.find(i=>i.name==='REFERENCE_TIME').selected=['TIME_NA','2026.007'];seed.inputs.push({name:'DATASET_BYTES',type:'number',value:'268435456'});seed.inputs.push({name:'WORK_ROWS',type:'number',value:'1000000'});
seed.cells=cells.map(({script,...c})=>c);fs.writeFileSync(path.join(__dirname,'definition.draft.json'),JSON.stringify(seed,null,2)+'\n');
fs.writeFileSync(path.join(__dirname,'build-status.json'),JSON.stringify({cells:cells.length,uncompiled:cells.filter(c=>!c.source).map(c=>c.id),generatedLengths:cells.map(c=>({id:c.id,length:c.source.length}))},null,2)+'\n');
console.log(JSON.stringify({cells:cells.length,uncompiled:cells.filter(c=>!c.source).map(c=>c.id)}));
module.exports={root,Script,cells,producers,start,finish,e,fresh,val,q,load,pub,group,filter,kf,sort,replace,find,match,copyRow,append,empty,enrich,ratio,fields,defaults};
